### ISSUE TITLE
Macedonian	

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#10]
Macedonian LC Romanization table was updated a year or two ago, and now two characters, Ѕ/ѕ and Џ/џ, use combining ligatures; the latter is now distinct from Serbian. (The Transliterator application does not reflect this update, so we have to keep an eye out for these characters and update them ourselves afterwards.) ScriptShifter is transliterating as would be appropriate for Serbian, but not for Macedonian.

**Comment by scossu** [comment]
Currently there is one table for both languages, `serbian_macedonian.yml`. The simplest and most proper way to resolve this would be to rename it to `serbian.yml`, and to create a new `macedonian.yml` that inherits from the former and adds the override(s).

**Comment by scossu** [comment]
@thisismattmiller I see you changed the tables, do you have test strings to add to the automated tests?
