### ISSUE TITLE
Provide s2r or r2s availability in the GET /languages response

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#112]
Would be useful for building interfaces to know what scripts had s2r, r2s or both capability in the languages response.

**Comment by scossu** [comment]
If you need this information in a pinch, you can use the `/table/<lang>` endpoint and check the JSON for the presence of the `script_to_roman` and/or `roman_to_script` sections. But I agree that this would be a useful shortcut to add to the languages endpoint.

**Comment by scossu** [comment]
This is being tackled as part of #104, which is a pretty large commit that will take some time, but it's in the works.

**Comment by scossu** [comment]
Fixed in #130.
