### ISSUE TITLE
Bibframe.org issue

### ISSUE THREAD

**Issue by quinnka2** [lcnetdev/scriptshifter#120]
I don't know if this is the best place to report these issues. But when using Scriptshifter in bibframe.org, we found these when using **Roman to script:**

- Get the error "SyntaxError: Unexpected token ... is not valid JSON" for these languages: Arabic (S2R), Bashkir, Buriat, Chinese (Hanzi), Greek (Classical), Hebrew, Karachay-Balkar, Kara-Kalpak, Komi, Korean, Korean (Last + first names only), Mongolian (Mongol bichig), Tamil
- For Russian and Ukranian, only the first word is transliterated correctly. The other words are all missing the first letter.

**Comment by scossu** [comment]
@thisismattmiller I have no insight in these errors, but the latest PR (still unmerged) should surface back end errors more transparently.

**Comment by scossu** [comment]
@quinnka2  for the Russian and Ukrainian errors, can you provide some sample strings with the expected outputs?

**Comment by scossu** [comment]
@quinnka2 for the second issue, please try again in test. See #121 .

**Comment by quinnka2** [comment]
@scossu I responded on #121. But here is the sample strings.

Original: Здравствуйте, меня зовут Келли

Transliterated script to Roman to: Zdravstvuĭte, meni︠a︡ zovut Kelli.


Zdravstvuĭte, meni︠a︡ zovut Kelli.

Transliterated Roman to script to: Здравствуйте, еня овут елли. Missing the м, з, and К.

**Comment by scossu** [comment]
Are you using the test site (https://scriptshifter-test.knowledgetx.com/?lang=russian)? I cannot reproduce your error. the fix may have not been pushed to production if you are testing there.

**Comment by quinnka2** [comment]
Yes, I was testing in production. It is fixed in test. Thanks!
