### ISSUE TITLE
Chinese (Hanzi)

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#13]
Generally following ALA/LC table, but some rarely used Chinese characters are not Romanized

An extra space always shown in between romanized character and punctuation; Most punctuation are romanized correctly (except for no romanization of wite corner brackets 『 』)

All "ü" (the only diacritic in ALA/LC Chinese Romanization Table) are showing incorrectly as "u"

**Comment by scossu** [comment]
Some additional information is needed: 

- Which rare Chinese characters are not romanized? These could be added to the table. 
- Which `u`s are showing incorrectly and which ones are legit? E.g.` 铝` transliterates `lü`, but I can't tell which other romanizations are expecting a "ü".

The extra space issue might be a logic problem. The transliteration table for Hanzi has an added space after each Romanized term, so if punctuation is encountered, there is an unwanted space. I thought I had addressed this but I have to look at the code and get back to this ticket. We may need to define a list of punctuation characters that suppress the space from the preceding token. This could be a good fit for the `on_tx_token_match` hook: read one extra character (without advancing the index), and if it is one of the punctuation symbols in the above mentioned list, strip whitespace from the end of the current match.

**Comment by scossu** [comment]
Closing this for now, as we are moving toward a whole new Chinese table. We'll open specific issues as they arise.
