### ISSUE TITLE
Adlam doesn't appear in pull down menu in editor

### ISSUE THREAD

**Issue by NeilSureshPatel** [lcnetdev/scriptshifter#17]
I double checked the Pulaar (Adlam) is present in the `index.yml` file but in the Marva Editor it doesn't appear as an option in the Romanization manual select pulldown menu. Is there another connection that has to be made?

**Comment by scossu** [comment]
I don't see Pular or Adlam in the main branch. That is what should be deployed in production. Can you verify which branch you saw this script in?

**Comment by NeilSureshPatel** [comment]
Hmm that is interesting because I am seeing a `pulaar.yml` file in in the [main branch](https://github.com/lcnetdev/scriptshifter/tree/main/scriptshifter/tables/data)? @thisismattmiller merged this in a couple weeks ago. PR [#15](https://github.com/lcnetdev/scriptshifter/pull/15)  I looking at the wrong thing?

**Comment by scossu** [comment]
I see it now, sorry I missed because it's not in alphabetical order.

It seems like the option is present in https://bibframe.org/scriptshifter @thisismattmiller is this the same endpoint used by Marva?

**Comment by thisismattmiller** [comment]
The bibframe.org marva editor is out of date, doesn't have the latest scriptshifter distribution, https://bibframe.org/scriptshifter is the latest and kept up to date for scriptshifter testing.

**Comment by NeilSureshPatel** [comment]
Ahh Thanks @scossu and @thisismattmiller. That is useful to know I didn't realize that about the Marva editor. I'll use [https://bibframe.org/scriptshifter](https://bibframe.org/scriptshifter).
