### ISSUE TITLE
Korean: FKR050

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#19]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1169-L1171:
```
   If StringRegExp($NClipB," 제[0-9]") Then
	  $NClipB = StringReplace($NClipB," 제"," 제 ")
   EndIf
```

Is the intent of this code to replace every instance of `제` followed by a digit with `제 `? In that case it seems to me that this may not yield the expected results, because as long as there is at least one occurrence of `제` followed by a digit, a space will be added to all `제` in the text, regardless of what follows them. 

In Python I'm proposing a regex substitution: 
```
data = re.sub(" 제([0-9])", "제 \\1", data)
```

@hyoungl let me know if I am indeed interpreting this correctly.

**Comment by hyoungl** [comment]
This part is to insert a space between 제 and any number in Hangul before romanization takes place, when it refers to an ordinal number according to the Hangul orthography

**Comment by scossu** [comment]
Got it. OK, I'll use my regex solution then.
