### ISSUE TITLE
Korean: OCLC Breve

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#20]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L964-L968: 

```
  If WinActive("Voyager Cataloging") Then
	  $NoOCLCBreve = "On"
   Else
	  $NoOCLCBreve = "Off"
   EndIf
```

@hyoungl How would this condition occur in ScriptShifter? Would it be always true, always false, or depend on some external factor?

**Comment by hyoungl** [comment]
ScriptShifter may not need this. Voyager and OCLC Connexion were different in entering a breve.
For example, Voyager had just "ŏ" for "어" while Connexion has "o" plus a breve for it.

**Comment by scossu** [comment]
Should we consider both types of input? `ŏ` and `o` + breve? ScriptShifter is used in Marva but it can also accept input from a variety of other sources.

**Comment by hyoungl** [comment]
It is all about the output and depends on which of the two Marva uses. You can just set on one or the other.

**Comment by scossu** [comment]
Thanks. I'll ask LC what their preference is. Probably we want to keep the output consistent wherever possible.

**Comment by scossu** [comment]
According to Randy, LC prefers the combining breve. At the moment I will leave the normalization where it is, maybe later we will want it in a more generic normalization function for all languages.
