### ISSUE TITLE
Korean: `isNonKor`

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#21]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1741-L1758 : 

```
   For $i = 0 To Ubound($Rule1)-1
	  If StringLeft(StringStripWS($TargetKorOrig,8),1)=$Rule1[$i] Then
		 $IsNonKor=$IsNonKor+1
	  EndIf
   Next
```
etc.

And further down https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1773:
```
If $Len > 1 and $IsNonKor=0 and $IsParticle=0 Then
```
This is the only place where `$isNonKor` is checked, and it's only checked if it equals 0. @hyoungl can I break the loops in LL1741-1750 as soon as `$isNonKor` > 0 to avoid redundant processing?

**Comment by hyoungl** [comment]
Yes, I think that makes more sense.

**Comment by scossu** [comment]
I compacted much of this logic by using booleans and Python built-ins.
