### ISSUE TITLE
Korean: translate FKR111

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#22]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/FKR_index.csv#L112 the Korean description of FKR111 is not translated. @hyoungl can you please translate it?

**Comment by hyoungl** [comment]
ㄹ + 모음/ㅎ/ㄹ,   ["lr","ll"] must be in the last of the array.
=

**Comment by scossu** [comment]
Thank you. Added to the CSV.
