### ISSUE TITLE
Korean: R2L flag

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#23]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1849:

```
   If $ConvertR2L = "On" AND $IsL_initial > 0 Then
```

`$ConvertR2L` is defined in L17 and looks like a user settings flag. 

@hyoungl does ScriptShifter need to distinguish between the two settings (it would be a major framework change)?

**Comment by hyoungl** [comment]
Under the current rules, which I believe is wrong, it is not needed.
I just put this code here in case that that rules are modified later, but it has not happened yet.

**Comment by scossu** [comment]
OK. I will remove the test for `$ConvertR2L = "On"`.
