### ISSUE TITLE
Korean: space check in names

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#26]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L469-L470: 

```
	  If StringInStr($TargetKorOrig," ",0,3)>0 Then
		 TrayTip("Error!",@LF & $TargetKorOrig & @LF & "may not be a Korean name (too many spaces)",10)
```

This condition seems to never be evaluated because it tests for 3 or more spaces, but on L459 it's tested for 2 or more spaces. @hyoungl is that correct? Can this  condition be removed?

**Comment by scossu** [comment]
Never mind. I misinterpreted the return value of `StringInStr`.

**Comment by hyoungl** [comment]
Originally there has to be only one space in personal names: always between last name and first name.
There is no middle name. Also note that women keep their family names, and marriage does not involve a change of last name.
Children used to get only paternal last name.
Recently, however, some people started use both paternal and maternal last names at the same time, although it is not officially accepted. This is the only case when we have two spaces in personal names.
I wanted to deal with this two-space cases.
