### ISSUE TITLE
Korean: duplicates in conversion map

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#27]
The (Hancha?) conversion map at https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L809 has some duplicates: 

- `['肖','소']` followed by `['肖','초']`
- `['葉','섭']` followed by `['葉','엽']`

Also, on https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1182

- `[' 백골단 ',' 백^골^단 ']` followed by `[' 백골단 ',' 백골^단 ']`

@hyoungl how is the substitution working here? It seems to me that the second duplicates will never be used.

**Comment by hyoungl** [comment]
For first two, you are right. Those last names have two different readings and it varies among people. So there is no way to predict how to read it. I just put all the Chinese characters used for last names, and users have to double-check.

For the third set, you are right too. The second [' 백골단 ',' 백골^단 ']  should be removed.

**Comment by scossu** [comment]
I will remove the duplicate.

For the first two, if there is no consensus or straightforward logic as to which reading to choose, shall we pick one and comment out the second one (maybe with some note if in the future some AI-based tool is able to discern)? Scriptshifter always chooses the first one in the list. Which one shall we pick?

**Comment by hyoungl** [comment]
It will be enough to pick the first one and to give a note to the other, as you said, until we have an AI-based tool.
