### ISSUE TITLE
Korean: breve normalization

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#28]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L295C1-L301C1 : 
```
	  If $OCLC="No" Then
		 Local $MARC8[4][2] = [["ŏ","ŏ"],["ŭ","ŭ"],["Ŏ","Ŏ"],["Ŭ","Ŭ"]]
		 For $i = 0 To Ubound($MARC8, 1) - 1
			$KorNameRom = StringRegExpReplace($KorNameRom, "\Q" & $MARC8[$i][0] & "\E",$MARC8[$i][1])
		 Next
	  EndIf

```

This is replacing the vowel + combining breve pair with a single vowel with breve. I remember discussing this as a general normalization step, and I verified this is running in my code.

However, the test strings for the expected results have the combined version, e.g. https://github.com/lcnetdev/scriptshifter/blob/korean/tests/data/sample_strings.csv#L791:

```
허상 과 실상 : 한국 정치 의 성숙 을 갈망 하며,Hŏsang kwa silsang: Han'guk chŏngch'i ŭi sŏngsuk ŭl kalmang hamyŏ
```

@hyoungl Were the test  strings written with `$OCLC="yes"` in mind? If so, shall I replace all the combined breve letters with their one-character versions?

**Comment by hyoungl** [comment]
$OCLC ="yes" is mainly for the situation where you have to use OCLC Connexion and Voyager.
K-Romanizer chooses different versions only on OCLC Connexion, thus checking $OCLC="yes" or "no" 
In Scriptshifter, do you need to deal with both cases, namely 1-character versions and 2-character versions?

**Comment by scossu** [comment]
No, we decided that we want to normalize all breves to the 1-character version. 

Shall I go ahead and change the test strings to the 1-character breve then?

**Comment by hyoungl** [comment]
Sure
