### ISSUE TITLE
Korean: spacing before punctuation

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#29]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1150 various punctuation signs surrounded by spaces are replaced by a code, e.g. `' : '` is replaced by `' SB16KQ '` (FKR050).

Then, in https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1257 this is being reverted after romanization, e.g. `' SB16KQ '` becomes `' : '` again (FKR066).

This for me results in a string such as `Hŏsang kwa silsang : Han'guk chŏngch'i ŭi sŏngsuk ŭl kalmang hamyŏ` instead of `Hŏsang kwa silsang: Han'guk chŏngch'i ŭi sŏngsuk ŭl kalmang hamyŏ` (note the extra space before `:`).

I didn't find a place in your code where space is removed before those punctuation signs. Can you point it out? 

Or can I simply replace `' SB16KQ '` with `': '` (and similar punctuation cases that don't have a leading space in Roman) in FKR066?

**Comment by hyoungl** [comment]
The spaces with ":"  or ";" were mainly meant for the cataloging punctuation.
But it would be better to stick with the punctuation of the original script in Scriptshifter.

**Comment by hyoungl** [comment]
That is correct in terms of cataloging, not of romanization, but it makes more sense that Scriptshifter retains the punctuation of the original text. Please remove the script which gives an extra space in front of ":" or ";".

**Comment by scossu** [comment]
OK, I took out the space before `.` `,` `:` and `;`. There may be other punctuation signs (`?`, `!`, etc.) that may need space removed, but I'm not sure if those occur in Korean and need to be adjusted.
