### ISSUE TITLE
Korean: Capitalization of test strings

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#30]
In some of the test strings, the romanization start with a capital letter. In some others it doesn't. 

If I run the tests without capitalizing the first word, most tests fail because the first word wouldn't be normally capitalized. If I capitalize the first word of all strings, the ones that don't start with a capital letter will fail. 

I am not sure if the tests are failing with capitalization off because of an error in my code that is not capitalizing a word that should always be so, or because some test strings have been capitalized on the first word.

Examples of test strings not starting with a capital: 

기술 경영 의 이해 -> kisul kyŏngyŏng ŭi ihae
기업 경영 국제 경영 부문 -> kiŏp kyŏngyŏng kukche kyŏngyŏng pumun
기업 경쟁력 강화 를 위한 내부 고발 과 윤리 경영 -> kiŏp kyŏngjaengnyŏk kanghwa rŭl wihan naebu kobal kwa yulli kyŏngyŏng

Strings starting with a capital: 

기업 이 알아야 할 100가지 소프트웨어 저작권 상담 사례 -> Kiŏp i araya hal 100-kaji sop'ŭt'ŭweŏ chŏjakkwŏn sangdam sarye
기업법 개설 제 12판 -> Kiŏppŏp kaesŏl che 12-p'an
기초 연구 투자 의 경제적 파급 효과 분석 -> Kich'o yŏn'gu t'uja ŭi kyŏngjejŏk p'agŭp hyogwa punsŏk

@hyoungl is there a fixed rule here?

**Comment by hyoungl** [comment]
Capitalization was not really the part of the test, because K-romanizer has three different key combos in terms of capitalization. For Scriptshifter, it makes more sense to capitalize the first letter by default.

**Comment by scossu** [comment]
Good to know. I will capitalize all the firsts then. Thanks.
