### ISSUE TITLE
Korean: incorrect romanization of `식민`

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#31]
`근대 와 식민 의 서곡` is romanized to `Kŭndae wa sikmin ŭi sŏgok`, but `Kŭndae wa singmin ŭi sŏgok` is expected.

Specifically, `식민` becomes `sikmin` instead of `singmin`. 

Debugging the script at the `식민` word, the code point conversion yields `i9#m20#f1~i6#m20#f4E`. 

FKR073÷100 don't change anything in this string.

This translates into `sikmin` as per FKR109. 

No other modification is made after that point. 

I verified the mappings I transcribed from K-Romanizer are identical to the original

@hyoungl Can you tell what is going wrong?

**Comment by scossu** [comment]
I found a bug in the code. The correct substitution is running now. Closing.

**Comment by hyoungl** [comment]
Great!
