### ISSUE TITLE
Korean: popular names missing

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#32]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1244 several popular name conversions are made. Some names used in test strings seem to be missing. 

The failing tests are:

`김 정일 공포 를 쏘아 올리다` -> `Kim chŏngil kongp'o rŭl ssoa ollida` (expected: `Kim Chŏng-il kongp'o rŭl ssoa ollida`)
`김 창모 의 대한 민국 선물 옵션 교과서` -> `Kim ch'angmo ŭi Taehan Min'guk sŏnmul opsyŏn kyogwasŏ` (expected: `Kim Ch'ang-mo ŭi Taehan Min'guk sŏnmul opsyŏn kyogwasŏ`)
`다석 류 영모 - 우리 말 과 우리 글 로 철학한 큰 사상가` -> `Tasŏk ryu yŏngmo - uri Mal kwa uri kŭl ro ch'ŏrhakhan k'ŭn sasangga` (expected: `Tasŏk Yu Yŏng-mo - uri mal kwa uri kŭl ro ch'ŏrhakhan k'ŭn sasangga` - I am not sure if this is a personal name)

Do these names need to be added to the list of special names?

**Comment by hyoungl** [comment]
That is normal, because K-Romanizer does not identify personal names. K-romanizer uses two different key combos to trigger personal names and general strings separately. Users have to identify personal names and use a correct key combo

**Comment by scossu** [comment]
Is it then not possible to test that string automatically?

**Comment by hyoungl** [comment]
There is no way to detect personal names at the moment. We will need a text analysis tool to do so.

**Comment by scossu** [comment]
OK, I will remove those test strings. Once I resolve all the other errors we might want to go over the remaining errors together so you can confirm which errors are due to personal names and which are not.

**Comment by hyoungl** [comment]
That is a comprehensive list of jurisdictions, and you can consider it closed.

**Comment by scossu** [comment]
Removed test strings with a mix of personal names in sentences.
