### ISSUE TITLE
Korean: unexpected vocalization

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#33]
`도란 도란 들려주는 말 이야기` transliterates into `Toran toran tŭllyŏjunŭn Mal iyagi` but the test string expects `Toran toran tŭllyŏ chunŭn mal iyagi`. 

I see a vocalization rule in FKR103 that inserts the `j` but nothing else changes the string from `tŭllyŏjunŭn`.

**Comment by hyoungl** [comment]
That is because of the different word division. The result is correct. The test string is from 도란 도란 들려 주는 말 이야기. So no problem here.

**Comment by scossu** [comment]
Ah, good. I can add the other string with the different word division and do two separate tests.
