### ISSUE TITLE
Korean: R to L option

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#35]
In https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1849 a `ConvertR2L` option is checked. 

As  for other options I encountered, I'm hoping that ScriptShifter could offer only one way of handling romanized strings. Which cases is this option relevant for, and can it be set to a fixed value?

**Comment by hyoungl** [comment]
ConvertR2L should be always on then. The rule cannot be changed in a matter of year or two.

**Comment by scossu** [comment]
OK, thanks. In this case, `내 안 의 리더십` will romanize as `Nae an ŭi lidŏsip`. Correct?

**Comment by hyoungl** [comment]
Correct.
