### ISSUE TITLE
Korean: FKR103 seems to run when it's not supposed to

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#37]
`일본 중심적` transliterates into `chungsimjŏk` but `chungsimchŏk` is expected. 

The code sequence is `i12#m13#f21~i9#m20#f16~i12#m4#f1E`

There is a substitution for `["f16~i12#","m~j"]` in FKR 103. 

This seems like the same problem as #36.

Regarding FKR103, I can see that in https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1673 a series of variables are checked, but as far as I can see, they are all set to 0 only once and never changed. Is FKR103 supposed to run on some conditions?

**Comment by scossu** [comment]
This seems to be an issue with FKR103. I will keep reporting further issues in this thread. 

`세법학` -> `Sebŏphak`; expected: `Sepŏphak`

substitution in FKR103: `["f0~i7#","~b"]`

**Comment by scossu** [comment]
`속문범` -> `songmunbŏm`; expected: `sok munbŏm`

Substitution in FKR103: `["f4~i7#","n~b"]`

**Comment by hyoungl** [comment]
> Actually, "chungsimjŏk" is correct with "j"

**Comment by hyoungl** [comment]
> `속문범` -> `songmunbŏm`; expected: `sok munbŏm`
> 
> Substitution in FKR103: `["f4~i7#","n~b"]`

Don't worry about "속문범" This is not a real word.

**Comment by scossu** [comment]
I corrected the two strings in the tests. `sok munbŏm` -> `songmunbŏm` only when in one word (`속문범`).
