### ISSUE TITLE
Korean: spaces around hyphen

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#38]
`한국 에서의 다문화 주의 - 현실 과 쟁점` is romanized as `Han'guk esŏŭi tamunhwa chuŭi - hyŏnsil kwa chaengchŏm` but `Han'guk esŏŭi tamunhwa chuŭi-hyŏnsil kwa chaengchŏm` is expected.

Is there supposed to be no spaces between the hyphen and the two words, even though there is in the script?

**Comment by hyoungl** [comment]
다문화 주의 should have been one word in the first place.
한국 에서의 다문화주의 - 현실 과 쟁점 = Han'guk esŏŭi tamunhwajuŭi - hyŏnsil kwa chaengchŏm
