### ISSUE TITLE
Breaking API change

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#39]
@thisismattmiller @kefo During the work in the `korean` branch it became necessary to change the output of the `/trans` API endpoint. Currently the output is a plain text string of the result; but K-Romanizer also displays important warnings on the Windows UI that need to be reproduced in the SS webapp, so I changed the output to a JSON object with the following structure: 

```
{
  "output": <string>,
  "warnings": <list of strings>
}
```

I imagine that this would break Marva, probably by dumping the JSON object as plain text in the wrong place. Can we coordinate the deployment of the Korean module with updates to Marva? 

The work-in-progress branch is named `korean`. I'm getting close to deploying at least the part that handles strings without personal names.

Also, I noticed that @thisismattmiller added some very useful JS in the index.html page that fills a results div with the output: https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/templates/index.html#L69-L115

Would you mind making a small improvement? It would be about adding another div with an ID of "warnings" or similar (milligram, the CSS framework I used, should have some classes to highlight it), hidden by default, that gets displayed and filled with the warnings (maybe one `<p>` or `<li>` per list item), and change the content of the results div to only the value of "ouptut"? Warnings would be empty most of the time so the warnings div should be hidden if they are empty.

**Comment by thisismattmiller** [comment]
Sure, I'll fix it in Marva when I update Scriptshifter after you make the change, so no need to wait for me on that point. I will make a pull request for the interface to change. Thanks.

**Comment by scossu** [comment]
@thisismattmiller I believe this is getting close to be ready for merging. Whenever you can update the UI display function I will open a PR, and then you can manage the deployment and Marva integration on your own terms.

**Comment by scossu** [comment]
Summarizing the breaking changes: 

1. The transliteration/transcription endpoint is now `/trans` for both UI and API calls; 
2. All parameters for `/trans` are passed in the POST body; 
3. The response is no longer plain text, but a JSON object with two keys: `output` and `warnings`.

The PR is ready for merging. Closing this issue as it was just for documentation purposes.
