### ISSUE TITLE
Korean: space before or after parentheses

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#43]
In #42 I noticed a few of failures like this one: 

```
- Chungso kiŏp ŭi chŏllyakchŏk sŏngkwa kwalli(BSC) ironp'yŏn
?        ^^
+ Chungsogiŏp ŭi chŏllyakchŏk sŏngkwa kwalli (BSC) ironp'yŏn
?        ^                                  +
Original: 중소 기업 의 전략적 성과 관리(BSC) 이론편
```

(In order: test result, expected result, original string; ignore the mismatch in the first part for now)

I imagine that whether the original was a typo or a legit string for Korean language, the Romanized string should have consistent spacing for parentheses and other punctuation.

@hyoungl  Is there a *generic* cataloging practice for this? I already added some normalization rules for other punctuation signs (`;`, `:`, etc.), but it would be good to have a general normalization table for all punctuation signs of this kind on all Romanized strings if guidelines exist in that direction.

**Comment by RandyBarry** [comment]
Unfortunately, there is no rule for how you might normalize punctuation and spacing. In library data, some punctuation marks are prescribed by ISBD (International Standard for Bibliographic Description) which usually requires spaces on both side of colon ( : ) and semi-colon ( ; ). This style of spacing is common in regular French text, but looks odd for English which does not normally place a space before colon or semicolon.  There is almost always a space after these marks, as there is after the comma and period, but in MARC there is no space after a final period in a field of text. The safest approach is probably not to change spacing at all during transliteration except for scripts that require it, like Chinese. From the example above, it looks like the best approach would have been to leave the spacing that occurred in the original script when converting to Latin, and vice versa.  (comment by Randy Barry)

**Comment by hyoungl** [comment]
Korean romanization rules have word division rules. While both 중소기업(no space) and 중소 기업 (one space) are both correct in Korean orthography, our romanization rules keeps the second one with space. So the catalogers should give a space even though the string on hand many not have a space. Then correct romanization will have a space.

**Comment by hyoungl** [comment]
I closed it by mistake.

**Comment by scossu** [comment]
So, what I'm hearing is this: we should not  change the original script spacing around  punctuation in general, but we should in Korean and Chinese (I'll leave the latter aside for now until I verify if it's being done). 

Correct?

**Comment by hyoungl** [comment]
Now I realized that I paid attention to the wrong part, which is the mismatch in the first part.
As for spacing around punctuation should be the same for Korean. No alteration from the original script.
Sorry about the confusion.

**Comment by scossu** [comment]
Very well. Thanks.
