### ISSUE TITLE
Korean: glottalization

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#46]
@hyoungl I am not clear of what happens with the glottalization process in https://github.com/lcnetdev/scriptshifter/blob/korean/scriptshifter/hooks/korean/Functions_KoreanRomanizer.au3#L1192-L1205 . 

There is a substitution of the `^` character (added earlier) with the string ` GLOTTAL `. Then, a few lines after, ` GLOTTAL ` is replaced with the empty string. I can't see any change happening in `KorRom`, which separates it from the Korean characters and returns it unchanged. In practice, the `^` character is simply removed with no further action. 

In the case of `결단력`, I get to `결 GLOTTAL 단+력` which eventually becomes `Kyŏli`. 

Am I missing something? Is this how it's supposed to work?

**Comment by hyoungl** [comment]
That explains why many examples Elaine provided is just "i". There must be something missing. I'll take a closer look and let you know.

**Comment by hyoungl** [comment]
Sorry, I closed it again by mistake.

**Comment by hyoungl** [comment]
This is the way how $RuleFortis set should work:
All the words in the $RuleFortis, the sound immediately following ^ will be romanized as voiced sounds, namely b, d, g, or j.
In most cases the results are correct, but in these words listed in $RuleFortis and many more it has to be voiceless sounds, namely p, t, k, or ch.
So what I did was to mark the position with "^" and notated it as " GLOTTAL " for my convenience. The notation does not have to be that way, of course.
Then the sounds immediately following ^ will be treated as initial sounds without affected by the voicing rule.
Afterwards the notation and spaces are deleted.

**Comment by scossu** [comment]
I think this is working as expected. I will reopen it if something possibly related to this comes up.
