### ISSUE TITLE
Korean: Name test failures

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#49]
Current list of failing names (from [Y. Lee's list](https://github.com/lcnetdev/scriptshifter/blob/korean/tests/data/script_samples/korean.csv): 
[korean_names_tests.log](https://github.com/lcnetdev/scriptshifter/files/12508380/korean_names_tests.log)

**Comment by scossu** [comment]
Looking at this error list I can't figure out if there is a number of logical errors or if it's a matter of adding some exception rules. 

This one stands out as a possible error in the test string: 

```
- Ŏ Yun-jŏk
?  ^
+ Ŏ,Yun-jŏk
?  ^
 : S2R transliteration error for korean_names!
Original: 어윤적
```

I haven't seen the comma notation elsewhere. Was that intended?

**Comment by hyoungl** [comment]
It is actually a very simple logic.
Func NameRomanizer() checks if there is a comma or a center dot.
If yes, it separates strings by the comma or the center dot and romanizes each name separately:  Func BatchRom()
If no, it just romanizes one name: Func KorNameRom20()

**Comment by hyoungl** [comment]
The notation you mentioned is for a different situation, where cataloging rules (not romanization rules) require a comma between the last name and the first name. This function should not turn on globally, because it applies only to certain fields like 100, 600, 700, etc.

**Comment by scossu** [comment]
Right, I was referring to the comma in the result rather than in the source.

So, the resolution for `Ŏ,Yun-jŏk` would be to replace the comma in the expected result with a space?

If you think that an extra option may be necessary for adding a comma in specific fields, I can add it. I tried to avoid per-script options so far, but if it's necessary, I'll add it.

**Comment by hyoungl** [comment]
Basically, there should not be a comma between the first name and the last name.
The logic was, romanization with no comma (a comma never occurs in Hangul script anyway).
If the Hangul script is in the field 100, 600, 700, or 800, then add a comma following the cataloging practice.

**Comment by scossu** [comment]
I added an option to specify the MARC field for Korean names. If the value is one of those you indicate, the Romanized text will add a comma after the last name.
