### ISSUE TITLE
Add Armenian Ligature Letters and a Diacritic

### ISSUE THREAD

**Issue by rrroche** [lcnetdev/scriptshifter#53]
Add five Armenian lowercase-only ligature letters and a diacritic:

ﬓ (U+FB13) should become mn
ﬔ (U+FB14) should become me
ﬕ (U+FB15) should become mi
ﬖ (U+FB16) should become vn
ﬗ (U+FB17) should become mkh
եվ  (U+0565) (U+057E) should become eʹv [the diacritic is (U+02B9)]
Եվ (U+0535) (U+057E) should become Eʹv [the diacritic is (U+02B9)]

**Comment by scossu** [comment]
Fixed in #54.
