### ISSUE TITLE
Non-slavic Cyrillic tables

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#64]
Complete Cyrillic tables for non-Slavic languages. 

@RandyBarry can you add a list of the languages involved here?

**Comment by RandyBarry** [comment]
asian_cyrillic  (this is a superset that covers many of the languages below but with some characters mapping to the most commonly used equivalents)
abkhaz_cyrillic
altai_cyrillic
azerbaijani_cyrillic
bashkir_cyrillic
buriat_cyrillic
chukchi_cyrillic
chuvash_cyrillic
dungan_cyrillic
even-evenki_cyrillic
gagauz_cyrillic
kalmyk_cyrillic
karachay-balkar_cyrillic
kara-kalpak_cyrillic
karelian_cyrillic
kazakh_cyrillic
khakass_cyrillic
khanty_cyrillic
komi_cyrillic
koryak_cyrillic
kyrgyz_cyrillic
lithuanian_cyrillic
mansi_cyrillic
mari_cyrillic
moldovan_cyrillic
mongolian_cyrillic
mordvin_cyrillic
nenets_cyrillic
ossetic_cyrillic
romani_cyrillic
shor_cyrillic
syriac_cyrillic
tajik_cyrillic
tatar_cyrillic
tatar-kryashen_cyrillic
turkmen_cyrillic
tuvinian_cyrillic
udmurt_cyrillic
uighur_cyrillic
uzbek_cyrillic
yakut_cyrillic
yuit_cyrillic
