### ISSUE TITLE
Korean: clarify FKR172÷179

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#65]
@hyoungl  I need some help clarifying what's happening in https://github.com/lcnetdev/scriptshifter/blob/main/legacy/Functions_KoreanHancha.au3#L241-L256 (repeated for FKR172 to 179 with different characters - comments are mine):
```
   ;FKR172
   If StringInStr($Hangul,"列")>0 THEN
	  StringReplace($Hangul,"列","X")
	  $R_Initial_Count = @Extended
          ; ^^ This gets the number of occurrences of "列"
	  For $i=1 to $R_Initial_Count
          ; ^^ loops for as many occurrences are found
		 $R_Initial_Str = StringMid($Hangul,StringInStr($Hangul,"列",0,1)-1,1)
                 ; ^^ This looks like is extracting one character before the current "列", right?
		 ClipPut($R_Initial_Str)
		 IdentifyCoda()
                 ; ^^ identifyCoda returns the modulo of the ASCII value of the character before "列" minus 44032, and 28
		 $CodaValue = ClipGet()
		 If $CodaValue = "0" OR $CodaValue = "4" OR StringToBinary($R_Initial_Str,4)<100 Then
                 ; ^^ What does StringToBinary? I looked at the AutoIt doc and examples online but I'm not sure how that can be compared with an integer (100). Would 100 be the code point value?
			$Hangul=StringReplace($Hangul,"列","열",1)
		 Else
			$Hangul=StringReplace($Hangul,"列","렬",1)
		 EndIf
                 ; These replacements ensure that the next loop looks for the next occurrence of "列"
	  Next
   EndIf
```

Thanks.

**Comment by hyoungl** [comment]
Those characters have two different readings depending on the value of the previous coda. You can collapse them into one, if you want to. I just wrote one function for one character, and then simply did copy-and-paste for all the others.

**Comment by scossu** [comment]
Thanks for confirming. I mainly wanted to clarify what `StringToBinary` is meant to yield. Since the string being passed is only one character, it should be the numeric code point value of the character, compared to an integer (100 would be the value of the letter `d`), correct?

**Comment by hyoungl** [comment]
That is basically  to decide what the previous character is in front of 烈.
I don't remember why I put StringToBinary in there, but maybe in case where the previous character is a symbol or punctuation?

**Comment by scossu** [comment]
What would StringToBinary yield for, e.g. `강`, and how would it compare to 100? 

I'm not sure if I'm using the correct function in my module and I'm unable to test on AutoIt because I'm not on Windows. In my Python code `강` would yield 44053.

**Comment by hyoungl** [comment]
$CodaValue = "0" means no coda. The syllable is composed of a consonant and a vowel.
$CodaValue = "4" means the coda is "ㄴ" = n.
As for StringToBinary($R_Initial_Str,4)<100, I think I added that for the case where a symbol comes in front of the character.

**Comment by hyoungl** [comment]
In short, the purpose of that part is to find if the immediately preceding sound is a vowel, or [n], or nothing.

**Comment by scossu** [comment]
I'm still not clear on what value StringToBinary would yield that can be compared with an integer. 

What would be the result of `StringToBinary($R_Initial_Str,4)` for `$R_Initial_Str = "강"`?

**Comment by hyoungl** [comment]
강 will be 44053.

**Comment by scossu** [comment]
Thanks, my implementation is correct then.
