### ISSUE TITLE
Additional Cyrillic scripts for Armenian &  Georgian

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#7]
Suggested additions: Cyrillic scripts like Abkhaz, Tatar, etc.

**Comment by scossu** [comment]
Abkhaz is addressed in #50 . Is there anything else aside from Tatar?

**Comment by rrroche** [comment]
Randy Barry has a whole set of files he would like to add over time. Is this something that needs to remain an open issue?

**Comment by rrroche** [comment]
To my knowledge, Georgian and Armenian do not use the Cyrillic script and they never really have. Hopefully Randy can chime in, thanks for tagging him.

**Comment by RandyBarry** [comment]
Rachel,You are correct. Armenian and Georgian use unique non-Latin scripts that are unrelated to the Cyrillic script. Cyrillic script has been adapted and used for many other languages of the Former Soviet Union and its sphere of influence. Some of these languages (for example, Azerbaijani) opted to adopt the Latin script after the end of the Soviet period. Many languages continue to use Cyrillic (such as Kazakh). Randy Barry - Рэнди Барри - ᠷᠧᠨᠳᠢ ***@***.*** Oct 16, 2023, at 08:55, rrroche ***@***.***> wrote:﻿
To my knowledge, Georgian and Armenian do not use the Cyrillic script and they never really have. Hopefully Randy can chime in, thanks for tagging him.

**Comment by scossu** [comment]
Then the title and description of this issue are in contradiction. If Tatar and Abkhaz support is the goal, we have both covered already. If anything else is needed for Armenian and Georgian, maybe we should try to reach out to the original reporter and ask them for clarification, but in any case we should close the issue. Agree?

**Comment by rrroche** [comment]
I agree.
