### ISSUE TITLE
Belarusian 

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#8]
I see  и here not being Romanized. During the meeting I said that Belarusian и И gets Romanized when typed (as I remembered it) which turns out is incorrect. It does not Romanize. 

Ѣ however, does not Romanize as Cammeron had reported. 

Example 1
![image](https://user-images.githubusercontent.com/1336458/212933530-0018477b-18b7-4f8d-b358-3530bf28f238.png)

Example 2
![image](https://user-images.githubusercontent.com/1336458/212933595-07c9cec5-ed50-4cd0-8107-d618aad4670e.png)

**Comment by scossu** [comment]
U+0418 (И), U+0438 (и) AND U+0462 (Ѣ) are effectively missing from Belarusian and parents.
