### ISSUE TITLE
Branching Language List, Favorite a Language via Cookie or Shortcut?

### ISSUE THREAD

**Issue by rrroche** [lcnetdev/scriptshifter#89]
I have not discussed this with anyone yet, but wanted to bring this up for consideration.

As more languages are added, a simple dropdown becomes more difficult to navigate easily. There are another 40+ languages that could be added with our current coding/language capabilities. Building in some way to make it easier to select the particular language a cataloger wants (for example, allowing someone to start typing the language name to skip to that option in the list), or favoriting or saving the language(s) a cataloger works with most frequently would be something I think a regular user of ScriptShifter would be interested in.

Or is there already some way to put an auto-fill in the URL for that? So a cataloger could save a shortcut that takes them to ScriptShifter with their language pre-selected?

**Comment by scossu** [comment]
This depends on the use you plan to make of the UI. Initially, this was conceived as a very simple front end for users to test the application during development, while relying on MARVA for everyday use. It only has a very minimal CSS framework and some hand-written Javascript functions for handling options. There are no built-in UI components to handle the kind of lookup that you describe.

If you think that the web front end may be used more frequently, it may be worth thinking about a redesign of the page to make it more robust. Let me know what you think.

**Comment by scossu** [comment]
A simple, bookmarkable shortcut to a specific language that I thought about could be appending a variable to the UI URL, e.g. https://bibframe.org/scriptshifter/?lang=chinese would set the language to Chinese.

**Comment by rrroche** [comment]
Thank you, Stefano, I like this idea.

I spoke to @thisismattmiller briefly and he agreed that some people would want to use ScriptShifter separately from MARVA, it sounded like he was thinking about adding a cookie to remember the last language at some point.

**Comment by scossu** [comment]
That sounds good. Implementing a URL-based setting should be relatively straightforward. A cookie-based approach would best be a suggested default to be be overridden by the URL method. We can talk about the cookie approach separately.

**Comment by scossu** [comment]
Fixed in v0.4.0.
